# Generated by Django 5.0.6 on 2024-07-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge2', '0002_carlist_chassisnumber_carlist_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='chassisnumber',
            new_name='chasisnumber',
        ),
    ]
