# Generated by Django 5.0.6 on 2024-07-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge2', '0003_rename_chassisnumber_carlist_chasisnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
