# Generated by Django 5.0.6 on 2024-07-07 19:35

import challenge2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge2', '0004_usersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='carlist',
            name='chasisnumber',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[challenge2.models.alphanumeric]),
        ),
    ]
