# Generated by Django 5.0.6 on 2024-07-07 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge2', '0005_showroommodel_alter_carlist_chasisnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showroom', to='challenge2.showroommodel'),
        ),
    ]
